name: roadmapped
description: "A comprehensive learning roadmap tracking application that helps users create, share, and follow structured learning paths"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  path_provider: ^2.1.2
  provider: ^6.1.2
  file_picker: ^6.1.1
  http: ^1.2.1
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.4+3
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
